CREATE DATABASE mytasks;

\c mytasks;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE tarefas (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Pendente',
    priority VARCHAR(50) NOT NULL,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

-- Inserindo usuários
INSERT INTO users (name, email) VALUES 
    ('Thiago Ferreira', 'thiagoferreira@gmail.com'),
    ('Marcelo Carboni', 'marcelocarboni@gmail.com'),
    ('Eduardo Correia', 'eduardocorreia@gmail.com'),
    ('Jonas Almeida', 'jonas.almeida@gmail.com'),
    ('Leonardo Silva', 'leonardo.silva@gmail.com'),
    ('Pedro Henrique', 'pedro.henrique@gmail.com'),
    ('Andre Luiz', 'andre.luiz@gmail.com'),
    ('Enzo Gabriel', 'enzo.gabriel@gmail.com'),
    ('Henrique Santos', 'henrique.santos@gmail.com'),
    ('Miguel Oliveira', 'miguel.oliveira@gmail.com'),
    ('Davi Costa', 'davi.costa@gmail.com'),
    ('Gustavo Lima', 'gustavo.lima@gmail.com'),
    ('Arthur Monteiro', 'arthur.monteiro@gmail.com'),
    ('Luiz Fernando', 'luiz.fernando@gmail.com'),
    ('Lucas Martins', 'lucas.martins@gmail.com'),
    ('Ravi Nascimento', 'ravi.nascimento@gmail.com'),
    ('José Carlos', 'jose.carlos@gmail.com'),
    ('Ana Clara', 'ana.clara@gmail.com'),
    ('Beatriz Silva', 'beatriz.silva@gmail.com'),
    ('Camila Oliveira', 'camila.oliveira@gmail.com'),
    ('Daniel Souza', 'daniel.souza@gmail.com'),
    ('Eduarda Lima', 'eduarda.lima@gmail.com'),
    ('Fernanda Costa', 'fernanda.costa@gmail.com'),
    ('Gabriel Almeida', 'gabriel.almeida@gmail.com'),
    ('Helena Martins', 'helena.martins@gmail.com'),
    ('Isabela Rocha', 'isabela.rocha@gmail.com'),
    ('João Pedro', 'joao.pedro@gmail.com'),
    ('Kauã Mendes', 'kaua.mendes@gmail.com'),
    ('Larissa Duarte', 'larissa.duarte@gmail.com'),
    ('Matheus Ribeiro', 'matheus.ribeiro@gmail.com'),
    ('Nathalia Farias', 'nathalia.farias@gmail.com'),
    ('Otávio Nunes', 'otavio.nunes@gmail.com'),
    ('Patrícia Cardoso', 'patricia.cardoso@gmail.com'),
    ('Rafael Teixeira', 'rafael.teixeira@gmail.com'),
    ('Sofia Monteiro', 'sofia.monteiro@gmail.com'),
    ('Thiago Azevedo', 'thiago.azevedo@gmail.com'),
    ('Vinícius Barros', 'vinicius.barros@gmail.com'),
    ('Yasmin Freitas', 'yasmin.freitas@gmail.com'),
    ('Zoe Santana', 'zoe.santana@gmail.com'),
    ('Arthur Campos', 'arthur.campos@gmail.com'),
    ('Bruna Ferreira', 'bruna.ferreira@gmail.com'),
    ('Carlos Eduardo', 'carlos.eduardo@gmail.com'),
    ('Débora Moraes', 'debora.moraes@gmail.com'),
    ('Elisa Vieira', 'elisa.vieira@gmail.com'),
    ('Fábio Cunha', 'fabio.cunha@gmail.com'),
    ('Giovanna Lopes', 'giovanna.lopes@gmail.com'),
    ('Hugo Batista', 'hugo.batista@gmail.com'),
    ('Bernardo Almeida', 'bernardo.almeida@gmail.com'),
    ('Vitor Mendes', 'vitor.mendes@gmail.com'),
    ('Carlos Augusto', 'carlos.augusto@gmail.com'),
    ('Felipe Santos', 'felipe.santos@gmail.com');

-- Inserindo tarefas
INSERT INTO tarefas (title, description, status, priority, user_id) VALUES
    ('Finalizar relatório', 'Concluir o relatório mensal de vendas', 'Em andamento', 'Alta', 1),
    ('Reunião com cliente', 'Agendar e participar da reunião com o cliente X', 'Pendente', 'Média', 2),
    ('Atualizar sistema', 'Realizar a atualização do sistema para a versão mais recente', 'Concluído', 'Baixa', 3),
    ('Planejar campanha', 'Criar o planejamento da nova campanha publicitária', 'Pendente', 'Alta', 4),
    ('Treinamento da equipe', 'Organizar o treinamento para novos colaboradores', 'Em andamento', 'Média', 5),
    ('Revisar contratos', 'Revisar todos os contratos pendentes do trimestre', 'Pendente', 'Alta', 6),
    ('Configurar backup', 'Implementar sistema de backup automático dos dados', 'Em andamento', 'Média', 7),
    ('Análise de performance', 'Analisar métricas de performance da aplicação', 'Pendente', 'Baixa', 8),
    ('Documentar APIs', 'Criar documentação completa das APIs do sistema', 'Em andamento', 'Média', 9),
    ('Testar segurança', 'Executar testes de penetração no sistema', 'Pendente', 'Alta', 10),
    ('Migrar banco de dados', 'Realizar migração do banco para novo servidor', 'Concluído', 'Alta', 11),
    ('Otimizar consultas', 'Otimizar consultas SQL para melhor performance', 'Em andamento', 'Média', 12),
    ('Implementar cache', 'Implementar sistema de cache para reduzir latência', 'Pendente', 'Baixa', 13),
    ('Monitorar logs', 'Configurar monitoramento automatizado de logs', 'Pendente', 'Média', 14),
    ('Criar dashboard', 'Desenvolver dashboard executivo com métricas', 'Em andamento', 'Alta', 15),
    ('Validar formulários', 'Implementar validação nos formulários do frontend', 'Concluído', 'Baixa', 16),
    ('Configurar CI/CD', 'Configurar pipeline de integração contínua', 'Pendente', 'Alta', 17),
    ('Refatorar código', 'Refatorar módulo de autenticação para melhor legibilidade', 'Em andamento', 'Média', 18),
    ('Automatizar deploy', 'Criar scripts de deploy automático para produção', 'Pendente', 'Média', 19),
    ('Corrigir bugs críticos', 'Resolver bugs críticos reportados pelos usuários', 'Em andamento', 'Alta', 20),
    ('Implementar PWA', 'Transformar aplicação em Progressive Web App', 'Pendente', 'Baixa', 21),
    ('Configurar SSL', 'Configurar certificados SSL em todos os ambientes', 'Concluído', 'Média', 22),
    ('Criar API REST', 'Desenvolver nova API REST para módulo de relatórios', 'Em andamento', 'Alta', 23),
    ('Implementar autenticação 2FA', 'Adicionar autenticação de dois fatores ao sistema', 'Pendente', 'Alta', 24),
    ('Otimizar imagens', 'Comprimir e otimizar todas as imagens da aplicação', 'Pendente', 'Baixa', 25);